import json,hashlib
from pathlib import Path
p=Path('./iclr_latex_v3/design_audit/second_coder_v1/independent')
s=json.loads((p/'SCOPES_SECOND_V1.json').read_text())
assert hashlib.sha256((p/'SCOPES_SECOND_V1.json').read_bytes()).hexdigest()==(p/'SCOPES_SECOND_V1.sha256').read_text().split()[0]
d={}
def add(i,rv,rr,pv,pr,iv,ir,ev):d[i]=[(rv,rr),(pv,pr),(iv,ir),ev]
lift='packet/sources/C01_main.pdf §4.1/Table 9 p.8; C01_supp.pdf D.2.1 printed pp.42–44 (PDF pp.20–22), five printed prompt examples.'
for i in ['C01-A','C01-B']:
 add(i,'Fail','Feature-name semantic tokens remain and are misassigned, rather than withdrawn. Correct association is not redefined as absence of semantic use.','Unclear','The claimed shuffle suggests inventory preservation, but example I duplicates semester and example II changes values. Executed templates are not established, so neither exact preservation nor actual data loss is verified.','Unclear','Free-text semantic oddity is acceptable, but the inconsistent printed field/value inventories prevent establishing stable routing/cardinality for the executed variant.',lift)
for i in ['C01-C','C01-D']:
 add(i,'Pass','Generic indexed fields and generic y withdraw the declared named feature/task context.','Unclear','The lone unnamed example changes category words to numeric codes; a complete fixed coding map is not documented. Two table variants are not separately specified. Format-II correct example also omits class size, making preservation across the worked examples unresolved.','Unclear','Common LM input/output alone does not settle the altered target/category coding and correspondence of both unnamed variants.',lift)
tab='packet/sources/C03_main.pdf §3.1–3.2 pp.3–4, serialization definitions; §5.1/Figure 2; Supplement §9 examples.'
add('C03-A','Fail','Meaningful names are permuted and retained. Misassignment is not withdrawal, regardless of fixed points.','Pass','A single fixed name permutation across examples retains values, positions, boundaries and task prompt/verbalizer under the same recipe.','Pass','Permuted strings remain valid name slots in the same list/text-to-label interface.',tab)
add('C03-B','Pass','Feature-name annotations are omitted from the ordered list.','Pass','The defined operation retains the feature values in their fixed arbitrary order and the separate task prompt. Explicit name prefixes are the tested annotation channel, not an independently protected scaffold; ordered slots and boundaries suffice here.','Pass','A list of values is valid text for the same LM and manually specified class verbalizer; no additional parsing or cardinality violation is evidenced.',tab)
add('C03-C','Fail','Permuted value tokens retain supplied semantic meanings but associate them with different observations; this is not a no-meaning input.','Fail','Ten uniform bins collapse continuous observations before permutation; the fixed mapping does not recover original continuous precision.','Pass','Changed value strings remain valid inputs in the same serialized slots and target interface.',tab)
plato='packet/sources/C04_main.pdf (Ruiz et al.), §§3.1–3.6 pp.4–6, Eq.(1) and Algorithm 1; §4.1 p.9, Tables 3–4.'
add('C04-A','Unclear','The induced subgraph removes broader-domain nodes from message passing, but the contrast does not specify whether fixed pretrained embeddings were recomputed. Broader-domain information could remain in those embeddings.','Pass','Feature nodes and observations remain; neighborhood changes are intrinsic to withdrawing broader nodes. The described PLATO recipe retains the protected inference scaffold, and no extra change is established.','Pass','An induced feature subgraph retains feature-node correspondence and feeds the same graph-to-weight predictor. Graph-size change is compatible with that interface.',plato)
add('C04-B','Pass','No KG explicitly means no auxiliary information or feature embeddings, yielding an ordinary MLP.','Fail','The first-layer weight-inference scaffold is replaced by directly fitted MLP weights. This changes the protected parameterization as well as removing KG information.','Pass','The replacement is an explicitly defined standard MLP with the same observed feature/target interface; architecture change does not itself create a routing or shape violation.',plato)
add('C04-C','Fail','Half of the edge information remains available; the declared use is KG edges as a whole, not only the realized deleted subset. Potential retained pretrained information does not weaken this failure.','Pass','Edge deletion changes tested connectivity while preserving feature nodes and the common PLATO prediction scaffold. No evidenced extra alteration is specified.','Pass','The model accepts a sparser KG with the same feature-node mapping; sparsity is the declared graph intervention, not evidence of an unintended missing-value or cardinality violation.',plato)
carte='packet/sources/C05_main.pdf §3.1/Figure 1 (numerical node initialization), §3 architecture; Appendix C.3/Figure 10 p.21.'
add('C05-A','Pass','The string-language-model initialization is replaced by n-gram MinHash encoding, removing the declared externally pretrained linguistic initialization. Lexical n-gram overlap is not the tested pretrained semantic use.','Unclear','Numeric initialization, nonsemantic string distinctions and encoder/training alignment after replacement are not documented sufficiently to establish protected information/scaffold preservation. Encoder replacement alone is not a failure.','Unclear','C.3 does not specify dimensional or numerical-node adaptation; a compatible implementation is possible but not established by the curve label.',carte)
add('C05-B','Unclear','Edge-info exclusion does not establish removal of column meaning from numerical nodes, which also use column embeddings. The exact operation is not reported.','Unclear','Cannot determine whether a neutral edge vector, edge removal or deleted computation preserves feature routing and the numerical representation.','Unclear','The label alone does not establish tensor/routing handling; no actual interface failure is demonstrated.',carte)
add('C05-C','Unclear','Column information may survive in numeric initialization, and edge exclusion is not operationally specified.','Fail','The named attention-layer exclusion additionally changes the protected attention scaffold, beyond the tested column-name information.','Unclear','Architecture removal is not automatically an interface failure, but the replacement routing/aggregation is unspecified.',carte)
feat='packet/sources/C06_main.pdf §3.1/Figure 2 pp.3–4, §4.2/Table 4 pp.7–8, Appendix A.2 and K.2/Table 18.'
add('C06-A','Pass','Omitting the feature-description block removes its explanatory definitions from rule generation; example-derived rules are allowed consequences.','Fail','The same block explicitly conveys types and possible categories, which are protected metadata in this scope. Those explicit facts are withdrawn together with definitions; examples alone do not document a lossless replacement for category/type information.','Unclear','The shared generation/parser recipe is described, but the ablated prompt and type/error handling do not establish compatible rule parsing after explicit schema information disappears.',feat)
add('C07-A','Pass','Replacing feature and target headers with indexed X names and Y withdraws the jointly declared informative header channel.','Pass','F.2 explicitly preserves the data, and indexed headers retain feature slots and target role. Target-header change is inside the declared scope.','Pass','Replacement strings occupy the same header positions and preserve the tabular LM evaluation interface.','packet/sources/C07_main.pdf §5.5; Appendix F.2 p.26 and Figure 12 p.27.')
ctx='packet/sources/C08_main.pdf §3.1 pp.3–4 (modality encoders and projection), §5.1 p.8, Table 2 semantic block p.9; Appendix A.4 pp.27–28.'
for i,encoder in [('C08-A','ordinal'),('C08-B','MinHash'),('C08-C','AutoGluon'),('C08-D','Gap')]:
 rv='Unclear' if i=='C08-C' else 'Pass'
 rr='The named AutoGluon feature encoder does not specify the configured string/text transformations, so complete removal of the pretrained linguistic pathway cannot be independently established.' if i=='C08-C' else f'Replacement of pretrained cell-language embeddings by {encoder} encodings removes the declared pretrained linguistic cell encoding. Any lexical structure retained by string encoders is outside this narrower use.'
 add(i,rv,rr,'Unclear',f'The {encoder} replacement is stated, but the per-arm handling of free text, unseen/missing categories, retained distinctions and fitting/pretraining alignment is materially underspecified. This is uncertainty, not an assumed failure from changing geometry.','Unclear','The architecture has a learned dimensional projection, so dimension changes can be valid. Per-encoder routing and compatibility are not specified sufficiently to certify the variant, particularly when replacing the text path by a different representation.',ctx)
add('C08-E','Pass','col1 through colN replace informative header meaning.','Pass','Indexed strings preserve distinct column positions; observations, modality encoders and predictor are unchanged by the defined header-only operation.','Pass','The replacement remains a string in the existing header encoder and projection path.',ctx)
add('C08-F','Pass','Original-name-only base lacks the additional descriptions; original name semantics are deliberately outside the tested increment.','Unclear','The generator sees five sampled rows, but their split and target access are unspecified. Matching the information available to the two arms cannot be established; no leakage is asserted.','Pass','Both original names and enriched name:description strings are compatible inputs to the same header encoder; provenance uncertainty belongs to Preservation.',ctx)
star='packet/sources/C09_main.pdf §4 Encoding/Fusion and Appendix A.1; §6 setup and Q3 p.9, Table 4 p.10; Appendix G.4/Table 31 p.53 and Table 32 p.54.'
add('C09-A','Pass','Name + Bin removes explicit quantile wording from the semantic branch. Quantile-related information inferable elsewhere is not the tested explicit wording.','Pass','Name/bin text and separate numerical input persist. §6 defines a common pretraining/evaluation setup for variants. Retraining under that recipe is allowed, not a checkpoint-equality requirement.','Pass','Shorter valid text enters the same semantic encoder and is fused with the same numerical-input branch.',star)
add('C09-B','Pass','Name removes numeric bin and quantile content from the verbalization; the illustrated generic Numeric marker carries type rather than numeric magnitude.','Pass','Raw numeric information remains in the separate standardized numerical branch, while names and missing markers remain. The shared variant recipe is stated in §6.','Pass','Generic name/type text is compatible with the existing text/numeric fusion, with no deletion of the numerical branch stated.',star)
tarte='CONTROL_CONSTRUCTION_V1_1.json C10-A/B, citing published §4.3/Figure 6 p.10; packet/sources/C10_author_mirror.pdf Figure 6 is preacceptance corroboration only, not authoritative published implementation evidence.'
add('C10-A','Unclear','The published condition label specifies removal of column names but not its implementation across all paths; complete semantic withdrawal including numerical initialization is unresolved.','Unclear','Neither published construction nor permissible corroboration establishes numerical/value routing and representation preservation for the name-removal operation.','Unclear','Name replacement, zeroing and pathway omission imply different interfaces; the published implementation is not accessible in this packet.',tarte)
add('C10-B','Pass','The published MinHash string-encoder condition replaces the externally pretrained linguistic encoder with a lexical encoding.','Fail','Random table-model weights replace Enriched YAGO4.5 table pretraining, an explicitly protected distinct component. The row therefore changes more than the tested string-encoder semantic use.','Unclear','The Ridge-on-embeddings output is named, but encoder dimension and numeric routing compatibility are not specified in authoritative published material available here.',tarte)
assert len(d)==len(s)==25
out=[]
for r in s:
 vals=d[r['Comparison ID']]
 for gate,pair in zip(['Removal','Preservation','Interface'],vals[:3]):r[gate]={'value':pair[0],'evidence':vals[3],'rationale':pair[1]}
 v=[x[0] for x in vals[:3]];a='No' if 'Fail' in v else 'Yes' if all(x=='Pass' for x in v) else 'Unclear'
 r['Admissible reference']={'value':a,'rationale':'; '.join(f'{g}={x}' for g,x in zip(['Removal','Preservation','Interface'],v))+f'; frozen rule therefore yields {a}.'}
 out.append(r)
(p/'CODES_SECOND_V1.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
from collections import Counter
print(Counter(r['Admissible reference']['value'] for r in out))
